CREATE TABLE [dbo].[ANI_CL_ANIO_D] (
    [ANI_ANIOPRE] NUMERIC (4)  NULL,
    [ANI_ESTADO]  NVARCHAR (1) NULL,
    [ANI_NROSOL]  NUMERIC (6)  NULL,
    [ANI_NROTRF]  NUMERIC (6)  NULL,
    [EVP_HABILIT] NVARCHAR (1) NULL,
    [EVP_USRACT]  NVARCHAR (8) NULL,
    [EVP_FCHACT]  DATETIME     NULL
);

