CREATE TABLE [dbo].[Contratos2] (
    [codigoproceso]                   NVARCHAR (200)  NULL,
    [DescripcionProceso]              NVARCHAR (200)  NULL,
    [codigocontrato]                  NVARCHAR (200)  NULL,
    [DescripcionContrato]             NVARCHAR (500)  NULL,
    [MonedaContrato]                  VARCHAR (100)   NULL,
    [MonedaProceso]                   VARCHAR (100)   NULL,
    [valorcontratado]                 NUMERIC (38, 6) NULL,
    [RPE]                             VARCHAR (100)   NULL,
    [razonsocial]                     NVARCHAR (150)  NOT NULL,
    [tipodocumento]                   VARCHAR (32)    NOT NULL,
    [numerodocumento]                 VARCHAR (100)   NULL,
    [esmipyme]                        BIT             NULL,
    [genero]                          VARCHAR (1)     NULL,
    [EstadoContrato]                  VARCHAR (100)   NULL,
    [fechaInicioContrato]             DATETIME2 (7)   NULL,
    [fechaFinContrato]                DATETIME2 (7)   NULL,
    [Fecha_inicio_ejecucion_contrato] DATETIME2 (7)   NULL,
    [Fecha_fin_ejecucion_contrato]    DATETIME2 (7)   NULL,
    [Certificate_code]                VARCHAR (150)   NULL,
    [UnidadCompra]                    NVARCHAR (150)  NULL,
    [CodigoSNIP]                      VARCHAR (100)   NULL,
    [FCH_INICIO_PUBLICACION]          DATETIME2 (7)   NULL,
    [FCH_INICIO_RECEP_OFERTAS]        DATETIME2 (7)   NULL,
    [FCH_ESTIMADA_ADJUDICACION]       DATETIME2 (7)   NULL,
    [MontoEstimado]                   NUMERIC (38, 6) NULL,
    [EstadoProceso]                   VARCHAR (100)   NULL,
    [URL]                             VARCHAR (145)   NULL,
    [CodigoUnidadCompra]              VARCHAR (100)   NULL,
    [FechaUltimaModificacion]         DATETIME        NOT NULL
);

