CREATE TABLE [dbo].[ContratosBK] (
    [NumeroLicitacion]           NVARCHAR (200) NULL,
    [FechaLicitacion]            DATETIME2 (7)  NULL,
    [EntidadContratanteOferta]   NVARCHAR (200) NULL,
    [IdEntidadContratanteOferta] NVARCHAR (200) NULL,
    [CategoriaContratacion]      NVARCHAR (500) NULL,
    [EstadoDetalle]              VARCHAR (100)  NULL,
    [IdOferta]                   VARCHAR (100)  NULL,
    [DescripcionOferta]          VARCHAR (300)  NULL,
    [MetodoContratacion]         VARCHAR (300)  NULL,
    [OfertaPeriodoDuracion]      INT            NULL,
    [OfertaPeriodoFechaInicio]   DATETIME2 (7)  NULL,
    [OfertaPeriodoFechaFin]      DATETIME2 (7)  NULL,
    [IdGanador]                  VARCHAR (250)  NULL,
    [IdProveedor]                NVARCHAR (150) NOT NULL,
    [ProveedorNombre]            NVARCHAR (150) NOT NULL,
    [IdQuejas]                   NVARCHAR (10)  NOT NULL,
    [IdContratos]                VARCHAR (100)  NULL,
    [ocid]                       VARCHAR (100)  NULL,
    [Comprador]                  VARCHAR (150)  NULL,
    [CompradorId]                VARCHAR (150)  NULL,
    [LanzamientoFecha]           DATETIME2 (7)  NULL,
    [urlApi]                     NVARCHAR (150) NOT NULL,
    [urlLicitacion]              NVARCHAR (150) NOT NULL,
    [FechaUltimaModificacion]    DATETIME       DEFAULT (getdate()) NOT NULL,
    [ValorContrato]              BIGINT         NULL,
    [FechaFirmaContrato]         DATETIME       NULL,
    [MonedaContrato]             VARCHAR (5)    NULL,
    [EstadoContrato]             VARCHAR (50)   NULL,
    [TipoDocumentoContrato]      VARCHAR (90)   NULL,
    [codigo_BPIN]                VARCHAR (50)   NULL,
    [Es_Covid]                   INT            NULL
);

