CREATE TABLE [dbo].[Indicadores2021] (
    [ANI_ANIOPRE]           NUMERIC (4)     NULL,
    [codigoprogramanegocio] INT             NULL,
    [NEN_CODIGO]            NUMERIC (2)     NULL,
    [ENT_CODIGO]            NUMERIC (3)     NULL,
    [TIP_CODIGO]            NUMERIC (1)     NULL,
    [PRO_CODIGO]            NUMERIC (3)     NULL,
    [SUB_CODIGO]            NUMERIC (2)     NULL,
    [PRY_CODIGO]            NUMERIC (2)     NULL,
    [IND_CODIGO]            NUMERIC (4)     NULL,
    [IND_NOMBRE]            VARCHAR (8000)  NULL,
    [IND_ANIOBASE]          NUMERIC (4)     NULL,
    [ENT_NOMBRE]            VARCHAR (60)    NULL,
    [PRO_NOMBRE]            VARCHAR (60)    NULL,
    [BCA_META]              NUMERIC (22, 2) NULL,
    [BCA_AVANCE]            NUMERIC (22, 2) NULL,
    [BCA_DENOMINADOR]       NUMERIC (22, 2) NULL,
    [BCA_PORCMETA]          NUMERIC (22, 2) NULL,
    [BCA_PORCAVANC]         NUMERIC (22, 2) NULL,
    [TIN_NOMBRE]            VARCHAR (50)    NULL,
    [TAM_NOMBRE]            VARCHAR (50)    NULL,
    [TDI_NOMBRE]            VARCHAR (50)    NULL,
    [IND_FRECUEN]           VARCHAR (50)    NULL,
    [PRY_CLASIFICACION]     VARCHAR (3)     NULL,
    [CODIGO_SNIP]           VARCHAR (60)    NULL
);

