CREATE TABLE [dbo].[ProgramaEjecucionContrato] (
    [Id]                  BIGINT        IDENTITY (1, 1) NOT NULL,
    [NivelEntidad]        INT           NOT NULL,
    [CodEntidad]          INT           NOT NULL,
    [Entidad]             VARCHAR (MAX) NOT NULL,
    [IdPrograma]          INT           NOT NULL,
    [CodProyActividad]    INT           NOT NULL,
    [NombreProyActividad] VARCHAR (MAX) NOT NULL,
    [PRY_Clasificacion]   VARCHAR (10)  NOT NULL,
    [Codigo_SNIP]         INT           NOT NULL,
    [CodObjeto]           INT           NOT NULL,
    [NombreObjeto]        VARCHAR (MAX) NOT NULL,
    [Fuente]              INT           NOT NULL,
    [Financiador]         INT           NOT NULL,
    [Departamento]        INT           NOT NULL,
    [Unidad]              NUMERIC (18)  NOT NULL,
    [Asiento]             INT           NOT NULL,
    [DOC_FHCLAB]          DATETIME      NOT NULL,
    [Ruc_Proveedor]       VARCHAR (50)  NOT NULL,
    [NombreProveedor]     VARCHAR (MAX) NOT NULL,
    [Comprobante]         VARCHAR (255) NOT NULL,
    [DocConcepto]         VARCHAR (MAX) NOT NULL,
    [CodigoContratacion]  VARCHAR (MAX) NULL,
    [Monto]               NUMERIC (18)  NULL,
    CONSTRAINT [PK_ProgramaEjecucionContrato] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ProgramaEjecucionContrato_Programa] FOREIGN KEY ([IdPrograma]) REFERENCES [dbo].[Programa] ([Id])
);

