CREATE TABLE [dbo].[ProgramaEjecucionContable] (
    [NivelEntidad]        INT            NULL,
    [CodEntidad]          INT            NULL,
    [Entidad]             VARCHAR (255)  NULL,
    [ClasePrograma]       INT            NULL,
    [CodPrograma]         INT            NULL,
    [NombrePrograma]      VARCHAR (255)  NULL,
    [CodProyActividad]    INT            NULL,
    [NombreProyActividad] VARCHAR (255)  NULL,
    [PRY_Clasificacion]   VARCHAR (10)   NULL,
    [Codigo_SNIP]         INT            NULL,
    [CodObjeto]           INT            NULL,
    [NombreObjeto]        VARCHAR (255)  NULL,
    [Fuente]              INT            NULL,
    [Financiador]         INT            NULL,
    [Departamento]        INT            NULL,
    [Unidad]              NUMERIC (18)   NULL,
    [Asiento]             INT            NULL,
    [DOC_FHCLAB]          DATETIME       NULL,
    [RUC_Proveedor]       VARCHAR (50)   NULL,
    [NombreProveedor]     VARCHAR (255)  NULL,
    [Comprobante]         VARCHAR (255)  NULL,
    [DOC_CONCEPTO]        NVARCHAR (MAX) NULL,
    [CodigoContratacion]  VARCHAR (60)   NULL,
    [Monto]               NUMERIC (18)   NULL,
    [FechaModificacion]   DATETIME       NULL,
    [EsCovid]             INT            NULL
);

