CREATE TABLE [consulta].[PND_x_Entidades_Presupuesto_STP] (
    [idPlan]                         INT             NOT NULL,
    [codPlan]                        INT             NULL,
    [nombrePlan]                     VARCHAR (255)   NULL,
    [idEje]                          INT             NOT NULL,
    [codEje]                         INT             NULL,
    [nombreEje]                      VARCHAR (255)   NULL,
    [idLinea]                        INT             NOT NULL,
    [codLinea]                       INT             NULL,
    [nombreLinea]                    VARCHAR (255)   NULL,
    [idObjetivoEstrategico]          INT             NOT NULL,
    [codObjetivoEstrategico]         INT             NULL,
    [nombreObjetivoEstrategico]      VARCHAR (255)   NULL,
    [descripcionObjetivoEstrategico] VARCHAR (255)   NULL,
    [idTipoObjetivo]                 INT             NOT NULL,
    [codTipoObjetivo]                INT             NULL,
    [nombreTipoObjetivo]             VARCHAR (255)   NULL,
    [idObjetivoEspecifico]           INT             NOT NULL,
    [codObjetivoEspecifico]          INT             NULL,
    [nombreObjetivoEspecifico]       VARCHAR (255)   NULL,
    [sector]                         VARCHAR (100)   NULL,
    [idNivel]                        INT             NOT NULL,
    [codNivel]                       INT             NULL,
    [nombreNivel]                    VARCHAR (255)   NULL,
    [idEntidad]                      INT             NOT NULL,
    [codEntidad]                     INT             NULL,
    [nombreEntidad]                  VARCHAR (255)   NULL,
    [año]                            INT             NULL,
    [planificado]                    NUMERIC (38, 2) NULL,
    [ejecutado]                      NUMERIC (38, 2) NULL
);

