CREATE TABLE [consulta].[Presupuesto_Vigente_x_Sector_MinHacienda] (
    [IdNegocioProyecto]       VARCHAR (19)    NULL,
    [codNivelEntidad]         VARCHAR (7)     NULL,
    [CodigoTipo]              INT             NULL,
    [CodigoPrograma]          INT             NULL,
    [CodigoProyecto]          INT             NULL,
    [AnioPresupuesto]         INT             NULL,
    [ClasePrograma]           VARCHAR (12)    NOT NULL,
    [NombreEntidad]           NVARCHAR (255)  NULL,
    [sectores]                VARCHAR (150)   NOT NULL,
    [Clasificacion]           VARCHAR (30)    NOT NULL,
    [PryClasificacion]        VARCHAR (24)    NOT NULL,
    [NombrePrograma]          NVARCHAR (255)  NULL,
    [Problematica]            NVARCHAR (2000) NOT NULL,
    [ResultadoIntermedio]     NVARCHAR (1000) NOT NULL,
    [ResultadoInmediato]      NVARCHAR (2000) NOT NULL,
    [NombreSubPrograma]       VARCHAR (60)    NULL,
    [NombreProyectoActividad] NVARCHAR (60)   NULL,
    [CodigoClasifFuncional]   INT             NOT NULL,
    [NombreFuente]            VARCHAR (60)    NOT NULL,
    [CodigoVersion]           INT             NOT NULL,
    [CodigoFuente]            INT             NOT NULL,
    [Nen_Codigo]              FLOAT (53)      NULL,
    [FinanciadorNombre]       VARCHAR (60)    NULL,
    [CodigoObjetoGasto]       FLOAT (53)      NULL,
    [NombreObjetoGasto]       NVARCHAR (255)  NULL,
    [Grupo]                   INT             NULL,
    [descripcionGrupo]        VARCHAR (28)    NOT NULL,
    [PresupuestoVigente]      NUMERIC (17)    NULL,
    [PresupuestoDisponible]   NUMERIC (17)    NULL,
    [PresupuestoAvance]       NUMERIC (17)    NULL
);

