CREATE TABLE [consulta].[VinculacionPND_Presupuesto_x_Entidad_STP] (
    [codEjeEstrategico]            INT           NULL,
    [nombreEjeEstrategico]         VARCHAR (256) NOT NULL,
    [codObjetivoEstrategico]       INT           NULL,
    [nombreObjetivoEstrategico]    VARCHAR (256) NOT NULL,
    [codObjetivoEspecifico]        INT           NULL,
    [nombreObjetivoEspecifico]     VARCHAR (256) NOT NULL,
    [codODS]                       INT           NULL,
    [nombreODS]                    VARCHAR (255) NULL,
    [descripcionODS]               VARCHAR (255) NULL,
    [codNivelEntidad]              VARCHAR (47)  NOT NULL,
    [entidad]                      VARCHAR (255) NULL,
    [siglaEntidad]                 VARCHAR (255) NULL,
    [numSector]                    INT           NULL,
    [nombreSector]                 VARCHAR (100) NULL,
    [clasificacionSector]          VARCHAR (100) NULL,
    [IdNegocioProyecto]            VARCHAR (255) NULL,
    [nombreProyecto]               VARCHAR (255) NULL,
    [aportePorcentualAlObjetivo]   FLOAT (53)    NULL,
    [aportePresupuestalAlObjetivo] FLOAT (53)    NULL,
    [presupuestoEjecutado]         INT           NOT NULL,
    [AnioPresupuesto]              INT           NOT NULL,
    [version]                      INT           NOT NULL
);

