CREATE TABLE [consulta].[Vinculacion_IndicadoresPND_Presupuesto_x_Entidades_STP] (
    [codEjeEstrategico]              INT            NULL,
    [nombreEjeEstrategico]           VARCHAR (255)  NULL,
    [codObjetivoEstrategico]         INT            NULL,
    [nombreObjetivoEstrategico]      VARCHAR (255)  NULL,
    [codObjetivoEspecifico]          INT            NULL,
    [nombreObjetivoEspecifico]       VARCHAR (255)  NULL,
    [codODS]                         BIGINT         NOT NULL,
    [nombreODS]                      NVARCHAR (MAX) NULL,
    [descripcionODS]                 NVARCHAR (MAX) NULL,
    [indicador]                      VARCHAR (255)  NULL,
    [Unidad/Escala]                  VARCHAR (255)  NULL,
    [añoBaseIndicador]               FLOAT (53)     NULL,
    [valorInidicador]                FLOAT (53)     NULL,
    [Meta 2023]                      FLOAT (53)     NULL,
    [Meta 2030]                      FLOAT (53)     NULL,
    [entidadReporta]                 VARCHAR (255)  NULL,
    [fuente]                         VARCHAR (255)  NULL,
    [entidad]                        VARCHAR (255)  NULL,
    [codNivelEntidad]                VARCHAR (5)    NULL,
    [IdNegocioProyecto]              VARCHAR (255)  NULL,
    [nombreProyecto]                 VARCHAR (255)  NULL,
    [aportePorcentualAlObjetivo]     FLOAT (53)     NULL,
    [aportePresupuestalAlObjetivo]   FLOAT (53)     NULL,
    [AnioPresupuesto]                INT            NOT NULL,
    [version]                        INT            NOT NULL,
    [descripcionEjeEstrategico]      VARCHAR (255)  NULL,
    [descripcionObjetivoEstrategico] VARCHAR (255)  NULL,
    [avance]                         FLOAT (53)     NULL
);

