//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlataformaTransparencia.Utilitarios {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosUtilidadesNegocio {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosUtilidadesNegocio() {
    ***REMOVED***
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlataformaTransparencia.Utilitarios.RecursosUtilidadesNegocio", typeof(RecursosUtilidadesNegocio).Assembly);
                    resourceMan = temp;
            ***REMOVED***
                return resourceMan;
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
        ***REMOVED***
            set {
                resourceCulture = value;
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a EJECUCI.
        /// </summary>
        internal static string CriterioEstadosEjecucion {
            get {
                return ResourceManager.GetString("CriterioEstadosEjecucion", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a EJECUTADO.
        /// </summary>
        internal static string CriterioEstadosEjecutado {
            get {
                return ResourceManager.GetString("CriterioEstadosEjecutado", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a APROBADO.
        /// </summary>
        internal static string CriterioEstadosPendientesSegunHistorico {
            get {
                return ResourceManager.GetString("CriterioEstadosPendientesSegunHistorico", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos, ha ocurrido un error..
        /// </summary>
        internal static string MensajeError {
            get {
                return ResourceManager.GetString("MensajeError", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Ente Territorial no es valido..
        /// </summary>
        internal static string MensajeErrorEnteTerritorial {
            get {
                return ResourceManager.GetString("MensajeErrorEnteTerritorial", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha enviado el filtro requerido o esta en un formato invalido.
        /// </summary>
        internal static string MensajeErrorFiltros {
            get {
                return ResourceManager.GetString("MensajeErrorFiltros", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a El periodo no es valido..
        /// </summary>
        internal static string MensajeErrorPeriodos {
            get {
                return ResourceManager.GetString("MensajeErrorPeriodos", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cero Registros Encontrados.
        /// </summary>
        internal static string MensajeNoHayProduccion {
            get {
                return ResourceManager.GetString("MensajeNoHayProduccion", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre.
        /// </summary>
        internal static string Meses {
            get {
                return ResourceManager.GetString("Meses", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todas las Fuentes.
        /// </summary>
        internal static string NombreFiltroRecursosTodasLasFuentes {
            get {
                return ResourceManager.GetString("NombreFiltroRecursosTodasLasFuentes", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departamento.
        /// </summary>
        internal static string nombreTipoEnteRepresentaDpto {
            get {
                return ResourceManager.GetString("nombreTipoEnteRepresentaDpto", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio.
        /// </summary>
        internal static string nombreTipoEnteRepresentaMunicipio {
            get {
                return ResourceManager.GetString("nombreTipoEnteRepresentaMunicipio", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a Region.
        /// </summary>
        internal static string nombreTipoEnteRepresentaRegion {
            get {
                return ResourceManager.GetString("nombreTipoEnteRepresentaRegion", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4.
        /// </summary>
        internal static string NumeroDeOtrosProyectosAMostrar {
            get {
                return ResourceManager.GetString("NumeroDeOtrosProyectosAMostrar", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        internal static string PorcentajeProyectosPorSectorMostrtar {
            get {
                return ResourceManager.GetString("PorcentajeProyectosPorSectorMostrtar", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a el, las,la,los,de,con,en,para,por,e,y.
        /// </summary>
        internal static string Preposiciones {
            get {
                return ResourceManager.GetString("Preposiciones", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4,68592950660633.
        /// </summary>
        internal static string ProyectoLatitudPorDefecto {
            get {
                return ResourceManager.GetString("ProyectoLatitudPorDefecto", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a -74,080810546875.
        /// </summary>
        internal static string ProyectoLongitudPorDefecto {
            get {
                return ResourceManager.GetString("ProyectoLongitudPorDefecto", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fuentes.
        /// </summary>
        internal static string TextoFiltroFuenteRecursos {
            get {
                return ResourceManager.GetString("TextoFiltroFuenteRecursos", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodos.
        /// </summary>
        internal static string TextoFiltroPeriodosFiscalizacion {
            get {
                return ResourceManager.GetString("TextoFiltroPeriodosFiscalizacion", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodos.
        /// </summary>
        internal static string TextoFiltroPeriodosRecursos {
            get {
                return ResourceManager.GetString("TextoFiltroPeriodosRecursos", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a /projectprofile/{0***REMOVED***.
        /// </summary>
        internal static string URLFichaProyectos {
            get {
                return ResourceManager.GetString("URLFichaProyectos", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Recursos/FichaRecursos?periodosRecursos={0***REMOVED***&amp;{1***REMOVED***={2***REMOVED***.
        /// </summary>
        internal static string URLFichaRecursos {
            get {
                return ResourceManager.GetString("URLFichaRecursos", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a /api/Proyectos/GetOtrosProyectosAprobados?periodosRecursos={0***REMOVED***&amp;fuentes={1***REMOVED***&amp;{2***REMOVED***={3***REMOVED***&amp;query={4***REMOVED***.
        /// </summary>
        internal static string URLProyectos {
            get {
                return ResourceManager.GetString("URLProyectos", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a /api/Proyectos/GetOtrosProyectosAprobados?{0***REMOVED***={1***REMOVED***&amp;{2***REMOVED***={3***REMOVED***&amp;query={4***REMOVED***.
        /// </summary>
        internal static string URLProyectosVerTodos {
            get {
                return ResourceManager.GetString("URLProyectosVerTodos", resourceCulture);
        ***REMOVED***
    ***REMOVED***
***REMOVED***
***REMOVED***
