CREATE TABLE [minhac].[EjecucionPresupuesto] (
    [ANIOPRESUP]            INT             NULL,
    [CodigoNivel]           INT             NULL,
    [CodigoEntidad]         INT             NULL,
    [CodigoTipo]            INT             NULL,
    [CodigoPrograma]        INT             NULL,
    [CodigoSubPrograma]     INT             NULL,
    [CodigoProyecto]        INT             NULL,
    [CodigoObjetivo]        INT             NULL,
    [CodigoClasifFuncional] INT             NOT NULL,
    [CodigoFuente]          INT             NULL,
    [CodigoVersion]         INT             NULL,
    [PAI_CODIGO]            INT             NULL,
    [DPT_CODIGO]            INT             NULL,
    [CodigoProducto]        INT             NULL,
    [PLANF1]                NUMERIC (15)    NULL,
    [EJEC1]                 NUMERIC (15)    NULL,
    [PLANF2]                NUMERIC (15)    NULL,
    [EJEC2]                 NUMERIC (15)    NULL,
    [PLANF3]                NUMERIC (15)    NULL,
    [EJEC3]                 NUMERIC (15)    NULL,
    [PLANF4]                NUMERIC (15)    NULL,
    [EJEC4]                 NUMERIC (15)    NULL,
    [PLANF5]                NUMERIC (15)    NULL,
    [EJEC5]                 NUMERIC (15)    NULL,
    [PLANF6]                NUMERIC (15)    NULL,
    [EJEC6]                 NUMERIC (15)    NULL,
    [USRING]                NVARCHAR (8)    NULL,
    [FCHING]                DATETIME        NULL,
    [USRACT]                NVARCHAR (8)    NULL,
    [FCHACT]                DATETIME        NULL,
    [ACC_CODIGO]            NUMERIC (5)     NULL,
    [PLANF7]                NUMERIC (15)    NULL,
    [EJEC7]                 NUMERIC (15)    NULL,
    [PLANF8]                NUMERIC (15)    NULL,
    [EJEC8]                 NUMERIC (15)    NULL,
    [PLANF9]                NUMERIC (15)    NULL,
    [EJEC9]                 NUMERIC (15)    NULL,
    [PLANF10]               NUMERIC (15)    NULL,
    [EJEC10]                NUMERIC (15)    NULL,
    [PLANF11]               NUMERIC (15)    NULL,
    [EJEC11]                NUMERIC (15)    NULL,
    [PLANF12]               NUMERIC (15)    NULL,
    [EJEC12]                NUMERIC (15)    NULL,
    [OBSERVACION]           NVARCHAR (1000) NULL
);

