CREATE TABLE [minhac].[ProyectoActividad] (
    [ANIOPRESUP]            INT             NULL,
    [CodigoNivel]           INT             NULL,
    [CodigoEntidad]         INT             NULL,
    [CodigoTipo]            INT             NULL,
    [CodigoPrograma]        INT             NULL,
    [CodigoSubPrograma]     INT             NULL,
    [CodigoProyecto]        INT             NULL,
    [CodigoUnidResponsable] INT             NULL,
    [NOMBRE]                NVARCHAR (60)   NULL,
    [NOMABR]                NVARCHAR (20)   NULL,
    [DESCRIP]               NVARCHAR (1000) NULL,
    [FCHING]                DATETIME        NULL,
    [USRING]                NVARCHAR (8)    NULL,
    [FCHACT]                DATETIME        NULL,
    [USRACT]                NVARCHAR (8)    NULL,
    [PAI_CODIGO]            INT             NULL,
    [DPT_CODIGO]            INT             NULL,
    [CIU_CODIGO]            INT             NULL,
    [PRY_OBJETIVO]          NVARCHAR (2000) NULL,
    [DIAGNOSTICO]           NVARCHAR (1000) NULL,
    [FCHCIERRE]             DATETIME        NULL,
    [USRCIE]                NVARCHAR (30)   NULL,
    [FCHCIE]                DATETIME        NULL,
    [FISUSRCIE]             NVARCHAR (30)   NULL,
    [FISFCHCIE]             DATETIME        NULL,
    [FISFCHCIERRE]          DATETIME        NULL,
    [CodigoClasifFuncional] NUMERIC (3)     NULL,
    [Clasificacion]         VARCHAR (50)    NULL
);

