CREATE LOGIN [mapainversiones_py]
    WITH PASSWORD = N'jaWypt!dq Kis***REMOVED***i{zQvfdpAHmsFT7_&#$!~<a|axyn#{okWS', SID = 0xA1ADFA37513DC649827319F6ACC07C45, DEFAULT_DATABASE = [PISGR_PY], DEFAULT_LANGUAGE = [Español], CHECK_POLICY = OFF;

