CREATE TABLE [mh].[ESTRUCTURA_PRESUPUESTARIA] (
    [idEstructuraPresupuestaria] INT             IDENTITY (1, 1) NOT NULL,
    [idPadre]                    INT             NULL,
    [tipoPresupuesto]            INT             NULL,
    [idFuenteFinanciamiento]     INT             NULL,
    [codigoEstructura]           INT             NULL,
    [alturaNivel]                INT             NULL,
    [idSector]                   INT             NULL,
    [codPrograma_subPrograma]    INT             NULL,
    [nombre]                     VARCHAR (255)   NULL,
    [nombreCorto]                VARCHAR (255)   NULL,
    [descripcion]                VARCHAR (255)   NULL,
    [año]                        INT             NULL,
    [es_imputable]               SMALLINT        NULL,
    [sigla]                      VARCHAR (255)   NULL,
    [baseLegal]                  VARCHAR (255)   NULL,
    [mision]                     VARCHAR (255)   NULL,
    [vision]                     VARCHAR (255)   NULL,
    [politica]                   VARCHAR (255)   NULL,
    [objetivo]                   VARCHAR (255)   NULL,
    [diagnostico]                VARCHAR (255)   NULL,
    [ruc]                        VARCHAR (255)   NULL,
    [presupuestoDestinado]       NUMERIC (15, 2) NULL,
    [resultadoEsperado]          VARCHAR (255)   NULL,
    [version]                    INT             NULL,
    [fechaCreacion]              DATETIME        NULL,
    [fechaActualizacion]         DATETIME        NULL,
    [usuarioResponasble]         VARCHAR (255)   NULL,
    CONSTRAINT [PK_ESTRUCTURA_PRESUPUESTARIA] PRIMARY KEY CLUSTERED ([idEstructuraPresupuestaria] ASC),
    CONSTRAINT [FK_ALTURA_ESTRUCTURA] FOREIGN KEY ([alturaNivel]) REFERENCES [mh].[ALTURA_NIVEL_ESTRUCTURA_PRESUPUESTARIA] ([idAlturaNivelEstructura]),
    CONSTRAINT [FK_ESTRUCTU_FK_ESTRUC_ESTRUCTU] FOREIGN KEY ([idPadre]) REFERENCES [mh].[ESTRUCTURA_PRESUPUESTARIA] ([idEstructuraPresupuestaria]),
    CONSTRAINT [FK_ESTRUCTU_FK_FUENTE_FUENTE_F] FOREIGN KEY ([idFuenteFinanciamiento]) REFERENCES [mh].[FUENTE_FINANCIAMIENTO] ([idFuenteFinanciamiento]),
    CONSTRAINT [FK_ESTRUCTU_FK_TIPOPR_ESTRUCTU] FOREIGN KEY ([tipoPresupuesto]) REFERENCES [mh].[ESTRUCTURA_PRESUPUESTARIA] ([idEstructuraPresupuestaria]),
    CONSTRAINT [FK_SECTOR_ESTRUCTURA] FOREIGN KEY ([idSector]) REFERENCES [mh].[SECTOR] ([idSector])
);

