CREATE TABLE [stp].[asignacionFinanciera] (
    [id]                   INT        NULL,
    [nivel_id]             INT        NULL,
    [entidad_id]           INT        NULL,
    [tipoPresupuesto_id]   INT        NULL,
    [programa_id]          INT        NULL,
    [subprograma_id]       INT        NULL,
    [proyecto_id]          INT        NULL,
    [producto_id]          INT        NULL,
    [objetoGasto]          INT        NULL,
    [fuenteFinanciamiento] INT        NULL,
    [organismoFinanciador] INT        NULL,
    [version]              INT        NULL,
    [año]                  INT        NULL,
    [planificadoEnero]     FLOAT (53) NULL,
    [ejecutadoEnero]       FLOAT (53) NULL,
    [planificadoFebrero]   FLOAT (53) NULL,
    [ejecutadoFebrero]     FLOAT (53) NULL,
    [planificadoMarzo]     FLOAT (53) NULL,
    [ejecutadoMarzo]       FLOAT (53) NULL,
    [planificadoAbril]     FLOAT (53) NULL,
    [ejecutadoAbril]       FLOAT (53) NULL,
    [planificadoMayo]      FLOAT (53) NULL,
    [ejecutadoMayo]        FLOAT (53) NULL,
    [planificadoJunio]     FLOAT (53) NULL,
    [ejecutadoJunio]       FLOAT (53) NULL,
    [planificadoJulio]     FLOAT (53) NULL,
    [ejecutadoJulio]       FLOAT (53) NULL,
    [planificadoAgosto]    FLOAT (53) NULL,
    [ejecutadoAgosto]      FLOAT (53) NULL,
    [planificadoSept]      FLOAT (53) NULL,
    [ejecutadoSept]        FLOAT (53) NULL,
    [planificadoOct]       FLOAT (53) NULL,
    [ejecutadoOct]         FLOAT (53) NULL,
    [planificadoNov]       FLOAT (53) NULL,
    [ejecutadoNov]         FLOAT (53) NULL,
    [planificadoDic]       FLOAT (53) NULL,
    [ejecutadoDic]         FLOAT (53) NULL
);

