CREATE TABLE [stp].[estructuraPresupuestaria] (
    [nivel_id]                       INT            NULL,
    [nivel_nombre]                   NVARCHAR (MAX) NULL,
    [nivel_nombrecorto]              NVARCHAR (MAX) NULL,
    [nivel_esimputable]              NVARCHAR (MAX) NULL,
    [nivel_año]                      INT            NULL,
    [entidad_id]                     INT            NULL,
    [entidad_nombre]                 NVARCHAR (MAX) NULL,
    [entidad_nombrecorto]            NVARCHAR (MAX) NULL,
    [entidad_sigla]                  NVARCHAR (MAX) NULL,
    [entidad_version]                INT            NULL,
    [entidad_ruc]                    NVARCHAR (MAX) NULL,
    [entidad_año]                    INT            NULL,
    [tipopresupuesto_id]             INT            NULL,
    [tipopresupuesto_nombre]         NVARCHAR (MAX) NULL,
    [tipopresupuesto_nombrecorto]    NVARCHAR (MAX) NULL,
    [tipopresupuesto_año]            INT            NULL,
    [programa_id]                    INT            NULL,
    [programa_codigoprograma]        INT            NULL,
    [programa_nombre]                NVARCHAR (MAX) NULL,
    [programa_nombrecorto]           NVARCHAR (MAX) NULL,
    [programa_codigodepartamento]    INT            NULL,
    [programa_año]                   INT            NULL,
    [subprograma_id]                 INT            NULL,
    [subprograma_coddepartamento]    INT            NULL,
    [subprograma_version]            INT            NULL,
    [proyecto_id]                    INT            NULL,
    [proyecto_nombre]                NVARCHAR (MAX) NULL,
    [proyecto_nombrecorto]           NVARCHAR (MAX) NULL,
    [proyecto_descripcion]           NVARCHAR (MAX) NULL,
    [proyecto_resultadoesperado]     NVARCHAR (MAX) NULL,
    [proyecto_coddepartamento]       INT            NULL,
    [proyecto_objetivoestrategicoid] INT            NULL,
    [proyecto_version]               INT            NULL,
    [proyecto_productoconcat]        NVARCHAR (MAX) NULL,
    [proyecto_año]                   INT            NULL,
    [producto_id]                    INT            NULL,
    [producto_nombre]                NVARCHAR (MAX) NULL,
    [producto_descripcion]           NVARCHAR (MAX) NULL,
    [producto_version]               INT            NULL,
    [producto_año]                   INT            NULL,
    [producto_productocontac]        NVARCHAR (MAX) NULL
);

